revert to shell.nix

diff --git a/home/justfile b/home/justfile
--- a/home/justfile
+++ b/home/justfile
@@ -4,11 +4,9 @@ default:
 
 # Setup a bitcoin core source directory
 setup source-dir:
-    if [ ! -d "{{source-dir}}" ]; then echo "Error: Bitcoin Core source directory {{source-dir}} does not exist" exit 1 fi
+    if [ ! -d "{{source-dir}}" ]; then echo "Error: Bitcoin Core source directory {{source-dir}} does not exist" exit 1; fi
+    cp ./env/.envrc bitcoin/shell.nix {{source-dir}}
     echo ".envrc"  >> {{source-dir}}/.gitignore
     echo "flake.nix"  >> {{source-dir}}/.gitignore
-    cp ./env/.envrc bitcoin/flake.nix {{source-dir}}
-    pushd {{source-dir}}
-    direnv allow
-    popd
+    cd {{source-dir}} && direnv allow
 
